### ISSUE TITLE
Passing variable into webified bash script

### ISSUE THREAD

**Issue by mihaigalos** [beefsack/script-httpd#12]
I cannot seem to be able to make the following minimal example run:

```bash
cat <<EOF > demo.sh
#!/bin/sh

VAR="\$(< /dev/stdin)"
echo \$VAR
EOF

sudo chmod +x demo.sh
docker run -it --rm -p 8080:80 -v $(realpath demo.sh):/script beefsack/webify:latest
```

and then:
```bash
curl http://localhost:8080 -d $(date '+%Y-%m-%d')
```

Am I doing something wrong? Expected output is the current date. Actual is a blank line.
I would like to help with extending `webify` if this is a missing feature and I find the time.

**Comment by mschirrmeister** [comment]
It seems the code pipes the http body to the script. So you have to use **stdin** instead of `$1`.
If that is good or the correct way, I am not sure.

Try the following in your bash script.

```
VAR="$(< /dev/stdin)"
echo $VAR
```

**Comment by mihaigalos** [comment]
Thanks for the idea, I've updated my initial minimal demo with what I've tried. Didn't work yet.

**Comment by beefsack** [comment]
Hi @mihaigalos, can you try using `#!/bin/bash` instead of `#!/bin/sh`?

**Comment by mihaigalos** [comment]
Hi @beefsack, I've tried that before asking. Can you reproduce it?

**Comment by mschirrmeister** [comment]
@mihaigalos Good question why it did not work for you. It worked for me with stdin, but I did not used docker. I just ran it natively on my Mac.

**Comment by Grynn** [comment]
I tried with the following which worked:

demo.sh:

```
#!/bin/sh

set -x

VAR=`cat /dev/stdin`
echo $VAR
```

The `set -x` produces useful logs.

Another issue:
Assumes that demo.sh is on the same host as docker (usually not the case on macOS).

**Comment by mihaigalos** [comment]
Thank you @Grynn - confirmed working in docker with your changes!
