### ISSUE TITLE
Feature/Enhancement Request: Cloud Deploy

### ISSUE THREAD

**Issue by Grynn** [beefsack/script-httpd#13]
Add support for runtimes:

`webify [--runtime=docker|azure|aws|gcloud|localhost] <command>`

Running `docker run -it -v script.sh:/script ...` does not work unless:

1. Host is linux (binding a single file, not folder with `-v` does not seem to work on macOS)
2. Docker engine is running on the same machine where the `docker run` command is being executed (often not the case; I am on macOS and use docker-machine).

The idea is for this to be a stepping stone to building docker images that can run as Azure Functions or other "serverless" runtimes.

Also keeps webify pure in that `--runtime` can default to "localhost" (i.e. just run webify locally as now).

## Runtime Docker

1. build docker image with script copied
2. either echo "image name" or `docker run -it --rm <image>` ?

## Runtime Azure

No idea yet, but https://github.com/Azure-Samples/functions-custom-handlers/tree/master/go might be a starting point

**Comment by beefsack** [comment]
Hi @Grynn, thanks for your suggestion!

I'd like to avoid cloud platform specific build integrations as there will be a lot of complexity to implement and maintain going forward. The focus here is for webify to be a very simple building block, completely decoupled from the application itself, as well as from build and deployment systems.

We currently use webify on both AWS and K8s, and the way we've achieved this is by using a `Dockerfile` to bake the script into an image directly inside our CI system. This should be platform agnostic as you could build from Windows, and Docker builds should be broadly available in CI systems.

Using `-v` is okay for playing around locally, but in any external environment it is definitely better to build an image and run that instead.

Example:

Your script that you would like to run (example.sh):

```bash
#!/bin/bash
echo "Hello world"
```

Dockerfile:

```
FROM beefsack/webify:latest
COPY example.sh /script
RUN chmod +x /script
```

Build:

```bash
$ docker build -t my/app .
$ # Realistically, you would then push the image to an image repository here, and then pull it from the target system
$ docker run -d -p 8080:80 my/app
$ curl http://localhost:8080
Hello world
```

Closing the issue for now, but we can revisit if this falls within scope later on.
