### ISSUE TITLE
想实现web展示pyspark的sql结果，如何实现？

### ISSUE THREAD

**Issue by wonb168** [beefsack/script-httpd#16]
命令行下不方便，怎么展现到web上。
本来执行的代码：
# 进入pyspark
pyspark
sql='select * from table2'
spark.sql(sql).show()
我想实现的效果是，写一个python函数，传入不同的页面，在web上展示sql的结果。

**Comment by beefsack** [comment]
I am working on the basis of the following Google translation:

> Inconvenient under the command line, how to display it on the web.
> Originally executed code:
> Enter pyspark
> 
> pyspark
> sql='select * from table2'
> spark.sql(sql).show()
> The effect I want to achieve is to write a python function, pass in different pages, and display the results of sql on the web.

As long as your script outputs to stdout it should work.
