### ISSUE TITLE
webify manager

### ISSUE THREAD

**Issue by eoli3n** [beefsack/script-httpd#17]
Hi, 
I'm searching for a solution to replace a project i use : https://github.com/eoli3n/shellcast
It's a nodejs app, that I didn't maintain, but which works well.

It is kind of webify but with those features:
- Multiple instances in a declarative yaml file
- a Single webserver which map commands to routes. http://localhost/command1 http://localhost/command2
- dynamic commands with php args -> shell args
- password protection for each webservices
- plain output (curl) and JS realtime shell output
- realtime highlighter by word|line in JS output

I'm still looking for a tool to replace it. I need same features but i can skip the js realtime shell output part.
If i don't find anything, i will maybe upgrade shellcast and fix vulnerabilities.

**Comment by eoli3n** [comment]
Actually, i just did an ``npm update`` without any problem. So shellcast is still on the road :)

**Comment by beefsack** [comment]
Thanks for the suggestion! Webify is designed to be incredibly simple, it sounds like what you are looking for would be served by either an application router or a more featureful HTTP server.
