### ISSUE TITLE
Webify service for encrypting files

### ISSUE THREAD

**Issue by mihaigalos** [beefsack/script-httpd#18]
I would like to webify a service for encrypting files (oversimplification, but let's just say they are short `yaml` files to be encrypted).
The way I envision interacting with `webify` is to curl it with:
* the `key` to be used in encryption (a separate file).
* the `yaml` to be encrypted.

Something like:
```bash
curl \
  -F "key=@/home/me/key" \
  -F "input_yaml=@/home/me/input.yaml" \
  localhost:8080
```

How do I store the `key` and `input.yaml` files on the backend side to start the process?

**Comment by beefsack** [comment]
Hi @mihaigalos, you could possibly create a new `Dockerfile` and use this image as a base. That would allow you to mount in any files or scripts you need.

A very brief example is https://github.com/beefsack/webify#building-a-new-image-using-official-image-as-base

**Comment by mihaigalos** [comment]
@beefsack:
I am quite familiar with `docker`, this is not what I want.

The question is how to I serialize a file from one machine to the running `webify` instance on another via `curl`.
