### ISSUE TITLE
Put some warning about security

### ISSUE THREAD

**Issue by BrunoVernay** [beefsack/script-httpd#7]
You might put a word about security :-)
Like "Make sure your machine is not accessible from Internet when exposing shell commands".

**Comment by beefsack** [comment]
Thanks for the suggestion! Not all cases are risky, but documentation will be expanded to cover cases where it is a bad idea to expose it publicly.

One design decision is that input should only be sent to stdin of the subprocess and not to the shell itself, so security is dependent on the process you are proxying to.

**Comment by buffet** [comment]
I'd still suggest putting that in bold in the readme. People are stupid. They do things not only before they think about them; sometimes they just don't think.
